config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ResponseConcerns
end

app/controllers/concerns/response_concerns.rb
module ResponseConcerns
  def json_error_response(messages, status = :unprocessable_entity)
    body = json_response_body('failure', messages)
    render status: status, json: body
  end

  def json_success_response(object, status = :ok)
    body = json_response_body('success', [], object)
    render status: status, json: body
  end

  def json_pagination(objects, serializer, status = :ok)
    render json: {
      pagination: {
        found: objects.total_count,
        pages: objects.total_pages,
        current_page: objects.current_page,
        per_page: objects.limit_value
      },
      entries: serialize_array(objects, serializer)
    }, status: status
  end

  private

  def json_response_body(result, messages = [], data = nil)
    {
      result: result,
      messages: messages,
      data: data
    }
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :schedule, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  def index
    # result = ScheduleIndexSchema.call(params)

    # if result.failure?
    #   return json_error_response(result.messages, :bad_request)
    # end

    json_pagination(
      ScheduleSearch.new.search,
      ScheduleSerializer
    )
  end

  def show
    json_success_response(
      ScheduleSerializer.new(schedule)
    )
  end

  def create
    time = ScheduleSearch.new.validate_time(params)

    if time.nil?
      json_error_response("Please, use a valid time", :bad_request)
      return
    end
    
    # result = ScheduleSchema.call(params)
    # if result.failure?
    #   return json_error_response(result.messages, :bad_request)
    # end
    # operation = Operations::Schedule::Create.new(user, room)
    # result = operation.call(result)

    result = Schedule.create(
      room_id: params[:room_id],
      status: 'active',
      start_at: params[:start_at], 
      expires_at: params[:expires_at]
    )
    # binding.pry
    if result.id.nil?
      return json_error_response(result.translated_errors, :unprocessable_entity)
    end

    # new_schedule = result.data[:new_schedule]
    json_success_response(ScheduleSerializer.new(result), :created)
  end

  def update
    schedule = ScheduleSearch.new.validate_existent_schedule(params)

    if schedule.nil?
      return json_error_response("Not exist an existent schedule", :bad_request)
    end

    result = schedule.update(
      room_id: params[:room_id],
      status: 'active',
      start_at: params[:start_at], 
      expires_at: params[:expires_at]
    )
    # binding.pry
    # result = ScheduleSchema.call(params)
    # if result.failure?
    #   return json_error_response(result.messages, :bad_request)
    # end

    # operation = Operations::Schedule::Update.new(user, room)
    # result = operation.call(result)

    if !result.present?
      return json_error_response(result.translated_errors, :unprocessable_entity)
    end

    # new_schedule = result.data[:updated_schedule]
    json_success_response(ScheduleSerializer.new(schedule), :ok)
  end

  def destroy
    if @schedule.nil?
      return json_error_response("Not exist an existent schedule to cancel")
    end

    @schedule.update!(status: false)
    json_success_response(ScheduleSerializer.new(@schedule))
  end

  private

  def schedule
    @schedule ||= Schedule.find_by(id: params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:room_id, :status, :start_at, :expires_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioNinja</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.datetime_select :start_at %>
  </div>

  <div class="field">
    <%= form.label :expires_at %>
    <%= form.datetime_select :expires_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Status</th>
      <th>Start at</th>
      <th>Expires at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.room_id %></td>
        <td><%= schedule.status %></td>
        <td><%= schedule.start_at %></td>
        <td><%= schedule.expires_at %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @schedule.room_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @schedule.status %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @schedule.start_at %>
</p>

<p>
  <strong>Expires at:</strong>
  <%= @schedule.expires_at %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>